//var hack_list = document.querySelectorAll('.linea_programa');
//var hacking = [];
//for(var i=0; i<hack_list.length;i++){
//	var curr_hack = hack_list[i];
//    var programm = {
//      'type': curr_hack.querySelector('.hack_tipo').innerHTML,
//      'name': curr_hack.querySelector('.hack_nombre').innerHTML,
//      'device': curr_hack.querySelector('.hack_disp').innerHTML,
//      'attack': curr_hack.querySelector('.hack_ataque').innerHTML,
//      'opponent': curr_hack.querySelector('.hack_rival').innerHTML,
//      'damage': curr_hack.querySelector('.hack_dano').innerHTML,
//      'burst': curr_hack.querySelector('.hack_R').innerHTML,
//      'target': curr_hack.querySelector('.hack_objetivo').innerHTML,
//      'skill': curr_hack.querySelector('.hack_habilidad').innerHTML,
//      'effect': curr_hack.querySelector('.hack_especial').innerHTML      
//    };
//    hacking.push(programm);
//}
//copy(hacking);
var hack_list = [{
  "type": "CLAW-1"
  , "name": "Blackout"
  , "device": "HD, HD+, AHD, EIHD, EIAHD"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "15"
  , "burst": "1"
  , "target": "Comms Equipment"
  , "skill": "Short Skill/ARO"
  , "effect": "Hacking Area. State: Disabled."
  , "class": "claw1"
}, {
  "type": "CLAW-1"
  , "name": "Gotcha!"
  , "device": "HD, HD+, AHD, EIHD, EIAHD"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "13"
  , "burst": "2"
  , "target": "TAG, HI, REM, Hacker"
  , "skill": "Short Skill/ARO"
  , "effect": "2 Turns. Hacking Area. State: IMM-1."
    , "class": "claw1"
}, {
  "type": "CLAW-1"
  , "name": "Overlord"
  , "device": "HD, HD+, AHD, EIHD, EIAHD"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "14"
  , "burst": "1"
  , "target": "TAG"
  , "skill": "Short Skill/ARO"
  , "effect": "Hacking Area. Breaker Spec. Ammo. State: POS."
    , "class": "claw1"
}, {
  "type": "CLAW-1"
  , "name": "Spotlight"
  , "device": "HD, HD+, AHD, EIHD, EIAHD"
  , "attack": "-3"
  , "opponent": "0"
  , "damage": "-"
  , "burst": "1"
  , "target": "-"
  , "skill": "Short Skill"
  , "effect": "Turn. Hacking Area. State: Targeted."
    , "class": "claw1"
}, {
  "type": "CLAW-2"
  , "name": "Expel"
  , "device": "HD+, AHD, EIHD, EIAHD, Bit, Gromoz"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "13"
  , "burst": "1"
  , "target": "Manned TAG"
  , "skill": "Short Skill/ARO"
  , "effect": "Hacking Area. The TAG expels its Pilot."
    , "class": "claw2"
}, {
  "type": "CLAW-2"
  , "name": "Oblivion"
  , "device": "HD+, AHD, EIHD, EIAHD"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "16"
  , "burst": "1"
  , "target": "TAG, HI, REM, Hacker"
  , "skill": "Short Skill/ARO"
  , "effect": "Hacking Area. State: Isolated"
    , "class": "claw2"
}, {
  "type": "CLAW-3"
  , "name": "Basilisk"
  , "device": "AHD, EIAHD"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "13"
  , "burst": "3"
  , "target": "TAG, HI, REM, Hacker"
  , "skill": "Short Skill/ARO"
  , "effect": "2 Turns. Hacking Area. State: IMM-1."
    , "class": "claw3"
}, {
  "type": "CLAW-3"
  , "name": "Carbonite"
  , "device": "AHD, EIAHD"
  , "attack": "+3"
  , "opponent": "0"
  , "damage": "13"
  , "burst": "2"
  , "target": "TAG, HI, REM, Hacker"
  , "skill": "Short Skill/ARO"
  , "effect": "Hacking Area. DT Spec. Ammo. State: IMM-1."
    , "class": "claw3"
}, {
  "type": "CLAW-3"
  , "name": "Total Control"
  , "device": "AHD, EIAHD"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "16"
  , "burst": "1"
  , "target": "TAG"
  , "skill": "Short Skill/ARO"
  , "effect": "Hacking Area. DT Spec. Ammo. State: POS"
    , "class": "claw3"
}, {
  "type": "GADGET-1"
  , "name": "Fairy Dust"
  , "device": "HD, HD+, DHD, EIHD, EVO, WHD"
  , "attack": "-"
  , "opponent": "-"
  , "damage": "-"
  , "burst": "1"
  , "target": "HI"
  , "skill": "Entire Order"
  , "effect": "Entire Order 2 Turns. All HIs gain Firewall MODs."
    , "class": "gadget"
}, {
  "type": "GADGET-1"
  , "name": "Lockpicker"
  , "device": "HD, HD+, DHD, EIHD, EVO, WHD"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "-"
  , "burst": "1"
  , "target": "-"
  , "skill": "Short Skill"
  , "effect": "Base to base contact. Can open/activate Security terrain."
    , "class": "gadget"
}, {
  "type": "GADGET-1"
  , "name": "Controlled Jump"
  , "device": "HD, HD+, DHD, EIHD, EVO, WHD"
  , "attack": "-"
  , "opponent": "-"
  , "damage": "-"
  , "burst": "1"
  , "target": ""
  , "skill": "Entire Order"
  , "effect": "Turn. +3 PH MOD to all Combat Jumps."
    , "class": "gadget"
}, {
  "type": "GADGET-2"
  , "name": "Assisted Fire"
  , "device": "HD, HD+, EIHD, EVO"
  , "attack": "-"
  , "opponent": "-"
  , "damage": "-"
  , "burst": "1"
  , "target": "REM"
  , "skill": "Entire Order"
  , "effect": "2 Turns. Target gains Marksmanship L2."
    , "class": "gadget"
}, {
  "type": "GADGET-2"
  , "name": "Enhanced Reaction"
  , "device": "HD, HD+, EIHD, EVO"
  , "attack": "-"
  , "opponent": "-"
  , "damage": "-"
  , "burst": "1"
  , "target": "REM"
  , "skill": "Entire Order"
  , "effect": "2 Turns. Target gains B2 in ARO."
    , "class": "gadget"
}, {
  "type": "SHIELD-1"
  , "name": "Exorcism"
  , "device": "HD, HD+, DHD, EIHD, EVO, WHD"
  , "attack": "0"
  , "opponent": "-3"
  , "damage": "18"
  , "burst": "2"
  , "target": "Possessed TAG"
  , "skill": "Short Skill"
  , "effect": "Cancels Possession. DT Spec. Ammo."
    , "class": "shield"
}, {
  "type": "SHIELD-1"
  , "name": "Hack Transport Aircraft"
  , "device": "HD, HD+, DHD, EIHD, EVO, WHD"
  , "attack": "-6"
  , "opponent": "-"
  , "damage": "-"
  , "burst": "1"
  , "target": "-"
  , "skill": "ARO"
  , "effect": "Face to Face Roll vs PH of the user of Combat Jump. Apply Dispersion rules."
    , "class": "shield"
}, {
  "type": "SHIELD-1"
  , "name": "U-Turn"
  , "device": "HD, HD+, DHD, EIHD, EVO, WHD"
  , "attack": "-"
  , "opponent": "-3"
  , "damage": "-"
  , "burst": "1"
  , "target": "Guided Spec. Ammo"
  , "skill": "ARO"
  , "effect": "Cumulative MOD to Attacks with Guided Spec. Ammo."
    , "class": "shield"
}, {
  "type": "SHIELD-2"
  , "name": "Breakwater"
  , "device": "HD+, DHD, EVO, WHD"
  , "attack": "0"
  , "opponent": "-6"
  , "damage": "-"
  , "burst": "1"
  , "target": "Hacker"
  , "skill": "Short Skill/ARO"
  , "effect": "Nullifies Hacking Attack."
    , "class": "shield"
}, {
  "type": "SHIELD-3"
  , "name": "Counterstrike"
  , "device": "DHD, WHD"
  , "attack": "-3"
  , "opponent": "-3"
  , "damage": "-"
  , "burst": "1"
  , "target": "Hacker"
  , "skill": "Short Skill/ARO"
  , "effect": "Reflects Hacking Attack back to attacker."
    , "class": "shield"
}, {
  "type": "SHIELD-3"
  , "name": "Zero Pain"
  , "device": "DHD, WHD"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "-"
  , "burst": "2*"
  , "target": "Hacker"
  , "skill": "Short Skill/ARO"
  , "effect": "Nullifies Hacking Attack. B2 in ARO."
    , "class": "shield"
}, {
  "type": "SWORD-1"
  , "name": "Brain Blast"
  , "device": "HD, HD+, EIHD, EVO, KHD, EIKHD"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "14"
  , "burst": "2"
  , "target": "Hacker"
  , "skill": "Short Skill/ARO"
  , "effect": "Hacking Area. Loss of 1 Wounds/STR."
    , "class": "sword"
}, {
  "type": "SWORD-2"
  , "name": "Redrum"
  , "device": "KHD, EIKHD, Asura"
  , "attack": "0"
  , "opponent": "-3"
  , "damage": "16"
  , "burst": "2"
  , "target": "Hacker"
  , "skill": "Short Skill/ ARO"
  , "effect": "Hacking Area. DT Special Ammo. Loss of 1 point of Wounds/STR."
    , "class": "sword"
}, {
  "type": "SWORD-2"
  , "name": "Skullbuster"
  , "device": "KHD, EIKHD"
  , "attack": "+3"
  , "opponent": "0"
  , "damage": "16"
  , "burst": "2"
  , "target": "Hacker"
  , "skill": "Short Skill/ ARO"
  , "effect": "Hacking Area. Breaker Special Ammo. Loss of 1 point of Wounds/STR."
    , "class": "sword"
}, {
  "type": "SWORD-2"
  , "name": "Trinity"
  , "device": "KHD, EIKHD, De Fersen"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "16"
  , "burst": "3"
  , "target": "Hacker"
  , "skill": "Short Skill/ ARO"
  , "effect": "Hacking Area. Shock Special Ammo. Loss of 1 point of Wounds/STR."
    , "class": "sword"
}, {
  "type": "UPGRADE"
  , "name": "Cybermask"
  , "device": "HD+, KHD, EIKHD"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "-"
  , "burst": "1"
  , "target": ""
  , "skill": "Entire Order"
  , "effect": "Replace user with Impersonation-2 Marker."
    , "class": "upgrade"
}, {
  "type": "UPGRADE"
  , "name": "White Noise"
  , "device": "HD+"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "-"
  , "burst": "1"
  , "target": ""
  , "skill": "Short Skill/ ARO"
  , "effect": "Turn. NFB. Hacking Area. Circular Template "
    , "class": "upgrade"
}, {
  "type": "UPGRADE"
  , "name": "Stop!"
  , "device": "EIAHD, Zoe"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "16"
  , "burst": "2"
  , "target": "TAG, HI, REM, Hacker"
  , "skill": "Short Skill/ ARO"
  , "effect": "2 Turns. Hacking Area. Breaker Spec. Ammo. State: IMM-1."
    , "class": "upgrade"
}, {
  "type": "UPGRADE"
  , "name": "Sucker Punch"
  , "device": "HD+, EIHD"
  , "attack": "0"
  , "opponent": "-3"
  , "damage": "16"
  , "burst": "1"
  , "target": "Hacker"
  , "skill": "Short Skill/ ARO"
  , "effect": "Hacking Area. DT Spec. Ammo. Loss of 1 Wounds/STR."
    , "class": "upgrade"
}, {
  "type": "UPGRADE"
  , "name": "Exile"
  , "device": "E-Drone, Samaritan"
  , "attack": "-"
  , "opponent": "-"
  , "damage": "16"
  , "burst": "1"
  , "target": "Fireteam member"
  , "skill": "Short Skill/ ARO"
  , "effect": "Hacking Area. State: Isolated. Fireteam cancellation."
    , "class": "upgrade"
}, {
  "type": "UPGRADE"
  , "name": "Goodnight"
  , "device": "E-Drone"
  , "attack": "+3"
  , "opponent": "-"
  , "damage": "16"
  , "burst": "2"
  , "target": "Remote Presence in Unconscious state"
  , "skill": "Short Skill"
  , "effect": "Hacking Area. Breaker Special Ammo. State: Dead."
    , "class": "upgrade"
}, {
  "type": "UPGRADE"
  , "name": "Maestro"
  , "device": "EIKHD, Scylla"
  , "attack": "+3"
  , "opponent": "-3"
  , "damage": "14"
  , "burst": "2"
  , "target": "Hacker"
  , "skill": "Short Skill/ ARO"
  , "effect": "Hacking Area. Breaker Special Ammo. State: Unconscious."
    , "class": "upgrade"
}, {
  "type": "UPGRADE"
  , "name": "Lightning"
  , "device": "Barid, Interventor"
  , "attack": "0"
  , "opponent": "-6"
  , "damage": "15"
  , "burst": "2"
  , "target": "Hacker"
  , "skill": "Short Skill/ ARO"
  , "effect": "Hacking Area. Breaker Special Ammo. Loss of 1 Wounds/STR."
    , "class": "upgrade"
}, {
  "type": "UPGRADE"
  , "name": "Icebreaker"
  , "device": "Barid, Custodier, Scylla"
  , "attack": "0"
  , "opponent": "0"
  , "damage": "12"
  , "burst": "2"
  , "target": "TAG, HI, REM, Hacker"
  , "skill": "Short Skill/ ARO"
  , "effect": "Hacking Area. Reduces BTS value to 0. State: IMM-1."
    , "class": "upgrade"
}, {
  "type": "GADGET-EVO"
  , "name": "Kaleidoscope"
  , "device": "EVO"
  , "attack": "-"
  , "opponent": "-"
  , "damage": "-"
  , "burst": "1"
  , "target": "Hacker"
  , "skill": "Entire Order"
  , "effect": "2 Turns. Target imposes a WIP-3 MOD."
    , "class": "evo"
}, {
  "type": "GADGET-EVO"
  , "name": "Overclock"
  , "device": "EVO"
  , "attack": "-"
  , "opponent": "-"
  , "damage": "-"
  , "burst": "1"
  , "target": "REM with Repeater"
  , "skill": "Entire Order"
  , "effect": "2 Turns. All targets gain B2 in ARO."
    , "class": "evo"
}, {
  "type": "GADGET-EVO"
  , "name": "Reboot"
  , "device": "EVO"
  , "attack": "-"
  , "opponent": "-"
  , "damage": "-"
  , "burst": "1"
  , "target": "TAG, HI, REM, Hacker"
  , "skill": "Entire Order"
  , "effect": "2 Turns. In Face to face Roll targets impose a WIP-3 when declaring Reset."
    , "class": "evo"
}, {
  "type": "GADGET-EVO"
  , "name": "TeamPro"
  , "device": "EVO"
  , "attack": "-"
  , "opponent": "-"
  , "damage": "-"
  , "burst": "1"
  , "target": "Fireteam"
  , "skill": "Entire Order"
  , "effect": "2 Turns. Allows naming a new Team Leader and the use of Fireteam Duo in Generic Armies."
    , "class": "evo"
}];

var temp = document.querySelector('#card');
var container = document.querySelector('.container');
var fragment = document.createDocumentFragment();
for (var i=0; i<hack_list.length; i++) {
    var programm = hack_list[i];
    var templ = temp.cloneNode(true);
    templ.content.querySelector('.card').classList.add(programm.class);
    templ.content.querySelector('#type').innerHTML = programm.type;
    templ.content.querySelector('#name').innerHTML = programm.name;
    templ.content.querySelector('#device').innerHTML = programm.device;
    templ.content.querySelector('#attack').innerHTML = programm.attack;
    templ.content.querySelector('#opponent').innerHTML = programm.opponent;
    templ.content.querySelector('#damage').innerHTML = programm.damage;
    templ.content.querySelector('#burst').innerHTML = programm.burst;
    templ.content.querySelector('#target').innerHTML = programm.target;
    templ.content.querySelector('#skill').innerHTML = programm.skill;
    templ.content.querySelector('#effect').innerHTML = programm.effect;

    fragment.appendChild(templ.content);
}
container.appendChild(fragment);